name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test:ci

      - name: Build PWA for GitHub Pages
        run: pnpm run build:pwa

      - name: Verify PWA build
        run: |
          echo "Checking PWA build artifacts..."
          ls -la dist/room-planner/browser/
          echo "Verifying manifest file..."
          test -f dist/room-planner/browser/manifest.webmanifest
          echo "Verifying service worker files..."
          test -f dist/room-planner/browser/ngsw.json
          test -f dist/room-planner/browser/ngsw-worker.js
          echo "Verifying .well-known directory..."
          test -d dist/room-planner/browser/.well-known
          echo "PWA build verification complete!"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: room-planner-build
          path: dist/room-planner/browser
