name: CI

on:
  push:
    branches:
      - main
      - v2/library-monorepo
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build library
        run: pnpm run build:lib

      - name: Test library
        run: pnpm run test:ci

      - name: Build sample app
        run: pnpm run build:sample

      - name: Verify library build
        run: |
          echo "Checking library build artifacts..."
          ls -la dist/room-planner-lib/
          echo "Verifying package.json..."
          test -f dist/room-planner-lib/package.json
          echo "Verifying compiled files..."
          test -f dist/room-planner-lib/esm2022/public-api.mjs
          test -f dist/room-planner-lib/fesm2022/room-planner.mjs
          echo "Library build verification complete!"

      - name: Verify sample app build
        run: |
          echo "Checking sample app build artifacts..."
          ls -la dist/room-planner-app/
          echo "Verifying browser directory..."
          test -d dist/room-planner-app/browser
          echo "Verifying index.html..."
          test -f dist/room-planner-app/browser/index.html
          echo "Sample app build verification complete!"

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: room-planner-lib
          path: dist/room-planner-lib

      - name: Upload sample app artifact
        uses: actions/upload-artifact@v4
        with:
          name: room-planner-sample-app
          path: dist/room-planner-app
