name: Library Tests

on:
  pull_request:
    paths:
      - 'projects/room-planner-lib/**'
      - 'package.json'
      - 'angular.json'
      - 'tsconfig.json'

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint library
        run: pnpm run lint

      - name: Test library
        run: pnpm run test:ci

      - name: Build library
        run: pnpm run build:lib

      - name: Verify library package
        run: |
          echo "📦 Library package verification..."
          ls -la dist/room-planner-lib/
          echo "✅ Package contents:"
          cat dist/room-planner-lib/package.json | jq '.'
          echo "✅ Checking public API exports..."
          test -f dist/room-planner-lib/public-api.d.ts
          echo "✅ Checking compiled bundles..."
          test -f dist/room-planner-lib/fesm2022/room-planner.mjs
          echo "📋 Library verification complete!"

      - name: Test library installation
        run: |
          echo "🧪 Testing library installation..."
          cd /tmp
          npm init -y
          npm install $GITHUB_WORKSPACE/dist/room-planner-lib
          echo "✅ Library installation test passed!"

      - name: Comment PR with library info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('dist/room-planner-lib/package.json', 'utf8'));

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📦 Library Build Summary

            ✅ **Library tests passed**
            ✅ **Library built successfully**

            **Package Details:**
            - **Name:** \`${packageJson.name}\`
            - **Version:** \`${packageJson.version}\`
            - **Size:** \`$(du -h dist/room-planner-lib | cut -f1)\`

            **Available in this PR:**
            - Library source code changes
            - Updated tests and documentation
            - Ready for testing in sample app

            **Next Steps:**
            - Test the library changes in the sample app
            - Verify all functionality works as expected
            - Ready for merge when approved
            `
            });
